# PharmGKB

Pharmacogenics Knowledge Base, or PharmGKB, is an onling repository of curated information about the complicated relationship between drug response and genetic makeup. This database includes several types of information on medication such as curated pathways, perscribing information, drug label annotations, clinical annotations and variant annotations. Relevant publications are also linked to the medication; which is where the information for annotations and pathways originate from.

The main purpose of PharmGKB is to readily offer accessible information to help facilitate personalized medicine. By understanging how a patient's individual genetic variation influences medication response, healthcare providers can make informed decisions on which medication to perscribe and ideal dosage. A personalized approach to medicine will lead to optimized treatment outcomes with minimized adverse reactions.

The PharmGKB website offers a user-friendly experience. In addition, PharmGKB also offers an Application Programming Interface, or API, with detailed documation on how to access and use the API. This allows the data too be programmatically accessed! The API provides endpoints for querying inforamtion about drugs, variant annotations, and more. For example, this API can be used to retreive information about a specific drug or to search for interactions.

# PharmGKB API Utilization



For PharmGKB, the API is utilized to run queries of different types of hypertensive medication to return variant annotations. As a test, ACE inhibitors, plain, is going to be used. This is a drug type with a PharmGKB ID of PA164712308.

### Requests
Requests is a python library used to make HTTP requests. This allows for easy of use to access APIs. This comes with tools that can be used to interact with APIs.
### JSON
JSON is a format that is the output for these APIs. For our purposes, the JSON libary is imported in order to provide fucntions for parsing and generating JSON data.
### Get
Get is a method from the requests libary, typically used to request data from a resource. This can be utilized by sending a GET request to retrieve the content of the page.

For our purposes, we will be utilizing GET to retrieve information from the API by specifying endpoints. Endpoints are a specific URL that serves as a destiantion for requests, we can utilize endpoints for an API to request specific information. For these databases, JSON will be the format in which the information is retrieved from the API.

# Creating a function to access the PharmGKB API

In [5]:
import requests #importing the requests libary to access the API
import json
def PharmGKB(id,output): #creating a function that will create a query with an ID and return a file of the variants
    baseurl = 'https://api.pharmgkb.org/v1/data/variantAnnotation?relatedChemicals.accessionId=' #this is the base url for API for PharmGKB
    url = baseurl + id #by combining the baserul and pharmgkb id for our drug, we get an endpoint to use for the API
    response = requests.get(url) #this will get the associated variant annotations for the drug
    data = response.json() #creates a dict from the JSON encododed result
    with open(output, 'w') as file: #opening a file in write mode
        json.dump(data, file) #writes data to file in JSON format

PharmGKB('PA164712308','pharmGKBdata.json') #testing the function wtih ACE Inhibitors, plain, PharmGKB ID

#This function will create a take a PharmGKB drug id and return a file of associated variant annotations in json format into a file

In [6]:
import os

def PharmGKB(id, output):
    baseurl = 'https://api.pharmgkb.org/v1/data/variantAnnotation?relatedChemicals.accessionId='
    url = baseurl + id
    response = requests.get(url)
    data = response.json()
    
    file_path = os.path.abspath(output)  # Get absolute file path
    with open(file_path, 'w') as file:
        json.dump(data, file)
    
    print(f"File saved at: {file_path}")  # Print the location

PharmGKB('PA164712308', 'pharmGKBdata.json')

File saved at: C:\Users\ian\Downloads\pharmGKBdata.json

# ClinVar
ClinVar is a freely accessible database of reports and interpretations of the clincial significance of variants for human health. ClinVar aggregates data from multiple sources like clinical testing laboratories, research studies, and literature. The information in ClinVar is more in the line of the relationship between genetic variants and human health and diseases, then specific to drug response like in PharmGKB. ClinVar also includes pharmacogenic variants as well, especially if they might have implications beyond simply drug response. Utilizing both databases, leads to more comprehensive and hollistic understanding of thec clinical significance of genetic variants of both disease suscenptability and personlized drug therapy. By incorporation information from both the disease and pharmocogenic vairants, health professionals can support and optimize personalized medicine.

# ClinVar API
Entrez is a search and retrieval system provided by the National Center of Biotechnology Information, or NCBI. It serves as an access point to numerous databases and resrouces. ClinVar is a part of the NCBI's Entrez system, and such such ClinVar can be accessed by using E-utilities. This allows for the use of functions such as esearch, esummary, elink, and efetch to access the ClinVar database.

Biopython is an open source libary for bioinformatics, this provides a set of tools such as the Entrez module. This provides a convenient way to to interact with Entrez databases, including ClinVar. For our purposes, we will be using the operation esummary. Esummary can be used to retrieve document summaries containing key information about a indiviudal records.

In [9]:
!pip install biopython 
#importing the biopython libary in order to access the entrez module

Collecting biopython
  Downloading biopython-1.85-cp312-cp312-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: numpy in c:\users\ian\anaconda3\lib\site-packages (from biopython) (1.26.4)
Downloading biopython-1.85-cp312-cp312-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 2.8/2.8 MB 41.3 MB/s eta 0:00:00
Installing collected packages: biopython
Successfully installed biopython-1.85

In [10]:
from Bio import Entrez #ClinVar can be easily accessed through the Entrez modul

In [11]:
def ClinVar(query, outputfile): #creating a function to esearch with a query in Clinvar
      Entrez.email = "ejm6256@nyu.edu" #suppling my email address for communication
      handle = Entrez.esearch(db='clinvar', sort='relevance', retmax='10', retmode='xml', term=query)
      #specifiying that the database to search in is ClinVar, to sort results by relevance, to return a max of 10 results, to retrieve the results in XML, and that the query is the query paramater
      results = Entrez.read(handle) #reads the search results from the search from handle to a dict
      IDlist = results["IdList"] #extracts the IDs from the search results in the dict and stores in IDlist
      handle = Entrez.esummary(db='clinvar', id=IDlist, retmode='json') #uses esummary operation to retreive summaries of records using the list of IDs from the search database
      with open(outputfile, "wb") as output: #decoding the bytes into a string before writing them to the file, else would give an error
          output.write(handle.read())

# Example usage:
ClinVar("NC_000003.11", "clinvar.json")

# DGIdb

The Drug-Gene Interaction database, or the DGIdb, is another resource that provides inforamtion about interactions between variants and drugs. Similarly to PharmGKB, it is an aggregation of annotated and curated data. It also aims to provide easily accessible information to facilitate personalized medicine apporaches. DGIdb has similarities to PharmGKB, however DGIdb is a more focused database. It mainly focuses on how specific drugs interacts with genes and the mechanisms; meanwhile PharmGKB has a broader focus such as genetype-phenotype assocaitions and clinical guidelines.

# DGIdb API

The DGIdb API can be used to query for drug-gene interactions. This api uses GraphQL queries to access the API. Accessing data from the DGIdb API is very similar to PharmGKB, the difference only in the query. GraphQL queries has a schema that define the data that is being requested to be retrieved. DGIdb API documentation has information on how the query is set up.

In [14]:
import requests #still using the requests library
import json #using json libary still
def DGIdb(drug, outputfile):
  query = """
{
  drugs(names: ["drug"]) {
    nodes {
      interactions {
        gene {
          name
          conceptId
          longName
        }
        interactionScore
        interactionTypes {
          type
          directionality
        }
        interactionAttributes {
          name
          value
        }
        publications {
          pmid
        }
        sources {
          sourceDbName
        }
      }
    }
  }
}"""

  url = 'https://dgidb.org/api/graphql'# The URL to the DGIdb GraphQL API endpoint

  # Make a request to the endpoint with the query
  response = requests.post(url, json={'query': query})
  data = response.json() #creates a dict from the JSON encododed result

  with open(outputfile, 'w') as file: #opening a file in write mode
      json.dump(data, file) #writes data to file in JSON format

In [15]:
DGIdb("ACE INHIBITOR", "DGIdbdata.json")

# Parsing the information

Three functions have been created for PharmGKB, ClinVar and DGIdb to query the database and return information. A lot of extraneous information was also retreived, thus it has to be parsed through in order to display only the relevant, needed information. Pandas is a data manipulation libary, providing data structures and functions to work with structured data fast and easy. This would be a great way to work through the JSON outputs. The data structure that will be utilized will be dataframes, a two dimensional data strucutre with columns.


# Pandas

The Pandas library will be importated for data manipulation and analysis which will be instrumental in parsing through the copious amounts of information that was aquired through the automated queries. The key component of Pandas that will be primarily used are dataframes, which are a two-dimensional tabular data structure very similar to a tabled.

# JSON
The JSON library will be imported in order to open and parse through JSON files.

### Parsing PharmGKB

The API returns nested data structures, thus parsing through the data will be needed. This data needs to be unpacked to filtered to retrieve only the relevant information. For PharmGKB, we are looking to extract the columns that provides a description, the interaction score, a sentence and the sequence location. This infromation is to help predict adverse drug reactions, help guide dosing, and to aim to improve therapeutic efficacy.

In [18]:
import pandas as pd
import json

##### Loading the JSON file into a dictionary
In order to start understanding the strucure of the inforamtion within the JSON file, the file is opened up and loaded into a dictionary and the dictionary keys are obtained. This will give the top level keys that are availible.

In [20]:
with open('C:/Users/ian/downloads/pharmGKBdata.json', 'r') as file: #opening PharmGKB file
    data = json.load(file) #loading the file data into a dict
keys = data.keys() #getting the dict keys
print(keys)

dict_keys(['data', 'status'])

##### Opening up the nested information within the dictionary
The dictionary will have multiple levels of nested information. On each level, there will be elements of either dictionaries or strings. Dictionaries will represent further nested information, and there can be multiple dictionaries on each level. For now, the dictionary will be opened up with the previously found key.

In [22]:
data['data'] #using the dict key to inside a nested level

[{'id': 699639186,
  'accessionId': 'PA166137232',
  'alleleGenotype': 'A',
  'comparison': 'G',
  'connWords1': {'id': 769229641,
   'resource': 'Phenotype Connecting words 1',
   'synonyms': [],
   'term': 'risk of',
   'termId': 'variantAnnotationPhenoConnWords1:769229641',
   'valid': True},
  'connWords2': {'id': 769229659,
   'resource': 'Phenotype or Gene to Drug Connecting Words',
   'synonyms': [],
   'term': 'when treated with',
   'termId': 'variantAnnotationPhenotypeConnWords2:769229659',
   'valid': True},
  'drugsConnWord': {'id': 827698395,
   'resource': 'Collection Operator - And/Or',
   'synonyms': [],
   'term': 'and',
   'termId': 'drugsConnWord:827698395',
   'valid': True},
  'formatVersion': 1,
  'history': [{'id': 1449761119,
    'date': '2018-11-05T14:06:42.621-08:00',
    'description': 'Updated OMB race to appropriate biogeographical group',
    'type': 'Update',
    'version': 0}],
  'isAssociated': True,
  'isPlural': False,
  'literature': {'id': 6462930,
   'title': 'Identification of genetic factors associated with susceptibility to angiotensin-converting enzyme inhibitors-induced cough.',
   '_sameAs': 'https://www.ncbi.nlm.nih.gov/pubmed/21052031',
   'authors': ['Grilo Antonio',
    'Sáez-Rosas María P',
    'Santos-Morano Juan',
    'Sánchez Elena',
    'Moreno-Rey Concha',
    'Real Luis M',
    'Ramírez-Lorca Reposo',
    'Sáez María E'],
   'crossReferences': [{'id': 699638774,
     'resource': 'PubMed',
     'resourceId': '21052031',
     '_url': 'https://www.ncbi.nlm.nih.gov/pubmed/21052031'},
    {'id': 1449245304,
     'resource': 'DOI',
     'resourceId': '10.1097/FPC.0b013e328341041c',
     '_url': 'http://dx.doi.org/10.1097%2FFPC.0b013e328341041c'}],
   'day': -1,
   'journal': 'Pharmacogenetics and genomics',
   'month': 1,
   'objCls': 'Literature',
   'page': '10-7',
   'pediatric': False,
   'pgkbPublication': False,
   'pubDate': '2011-01-01T00:00:00-08:00',
   'pubmedMeshTerms': [],
   'terms': [],
   'type': 'Literature',
   'volume': '21',
   'year': 2011},
  'location': {'id': 699639187,
   'buildVersion': 'hg19',
   'chromosomeId': 'PA527',
   'chromosomeName': 'chr3',
   'copyNumber': '1',
   'diplotypes': [],
   'displayName': 'rs2016848',
   'genes': [{'objCls': 'Gene',
     'id': 'PA30864',
     'symbol': 'MME',
     'name': 'membrane metalloendopeptidase'}],
   'gpPosition': 154858685,
   'haplotypes': [],
   'linkedObjects': [{'objCls': 'Variant',
     'id': 'PA166156337',
     'symbol': 'rs2016848',
     'name': 'rs2016848'}],
   'refSeqPosition': -1,
   'rsid': 'rs2016848',
   'tagGene': False,
   'type': 'SNP',
   'variant': {'objCls': 'Variant',
    'id': 'PA166156337',
    'symbol': 'rs2016848',
    'name': 'rs2016848'}},
  'metabolizers1': [],
  'metabolizers2': [],
  'objCls': 'Variant Phenotype Annotation',
  'pediatric': False,
  'phenotypeCategories': [{'id': 769229935,
    'resource': 'Phenotype Categories',
    'synonyms': [],
    'term': 'Toxicity',
    'termId': 'secondaryCat:769229935',
    'valid': True}],
  'phenotypes': [{'id': 94810473,
    'disease': {'objCls': 'Disease', 'id': 'PA443803', 'name': 'Cough'},
    'phenotype': 'Cough',
    'phenotypeContext': 'Disease'}],
  'polarity': {'id': 769229639,
   'resource': 'Polarity',
   'synonyms': [],
   'term': 'increased',
   'termId': 'variantAnnotationPolarity:769229639',
   'valid': True},
  'populationPhenotypes': [{'id': 699639186,
    'disease': {'objCls': 'Disease', 'id': 'PA444552', 'name': 'Hypertension'},
    'phenotype': 'Hypertension',
    'phenotypeContext': 'Disease'}],
  'populationTerm': {'id': 769229662,
   'resource': 'Population',
   'synonyms': [],
   'term': 'in people with',
   'termId': 'variantAnnotationPhenotypeConnWords3:769229662',
   'valid': True},
  'relatedChemicals': [{'objCls': 'Chemical',
    'id': 'PA164712308',
    'name': 'Ace Inhibitors, Plain'}],
  'relatedVariations': [{'objCls': 'Allele',
    'id': 'PA166372218',
    'symbol': 'CA1412780004',
    'name': 'NM_007289.4(MME):c.957+604G='},
   {'objCls': 'Allele',
    'id': 'PA166372219',
    'symbol': 'CA15256972',
    'name': 'NM_007289.4(MME):c.957+604G>A'}],
  'score': 2.5,
  'scoreDetails': {'step5A': 1.0,
   'step5B': 1.0,
   'chosenSpId': 699639198,
   'step1Score': 1.0,
   'step2Score': 1.0,
   'step3Score': 0.5,
   'step4Score': 0.0,
   'totalScore': 2.5,
   'chosenSpIndex': '1 of 1',
   'generatedDate': '2021-03-20T22:23:42.587-07:00',
   'variantAnnotationId': 699639186},
  'sentence': 'Allele A is associated with increased risk of Cough when treated with Ace Inhibitors, Plain in people with Hypertension as compared to allele G.',
  'sequenceLocation': {'id': 1448059186,
   'altHgvs': {},
   'assembly': 'GRCh37',
   'begin': 154858685,
   'end': 154858685,
   'intronicOffset': 0,
   'referenceAllele': 'G',
   'referenceHgvs': 'NC_000003.11:g.154858685=',
   'sequence': {'id': 1447949553,
    'name': '[GRCh37]chr3',
    'resource': 'RefSeq DNA',
    'resourceId': 'NC_000003.11',
    '_url': 'https://www.ncbi.nlm.nih.gov/nuccore/NC_000003.11'},
   'source': 'dbSnp',
   'type': 'genomic',
   'variantAlleles': ['A', 'C', 'T'],
   'variantHgvs': ['NC_000003.11:g.154858685G>A',
    'NC_000003.11:g.154858685G>C',
    'NC_000003.11:g.154858685G>T']},
  'significance': {'id': 769229666,
   'resource': 'Association Significance',
   'synonyms': [],
   'term': 'yes',
   'termId': 'variantAnnotationSignificance:769229666',
   'valid': True},
  'studyParameters': [{'id': 699639198,
    'characteristics': 'hypertension',
    'characteristicsType': 'Study Cohort',
    'confidenceIntervalStart': 1.232,
    'confidenceIntervalStop': 2.615,
    'frequencyInCases': -1.0,
    'frequencyInControls': -1.0,
    'pediatric': False,
    'populationEthnicity': {'custom': False,
     'ethnicities': [],
     'mixed': False,
     'notes': 'Spain',
     'unknown': True},
    'populationTypes': [],
    'pvalue': 0.002,
    'pvalueOp': {'id': 1183492001,
     'resource': 'Equality Symbols',
     'synonyms': [],
     'term': '=',
     'termId': 'equality:1183492001',
     'valid': True},
    'pvalueString': '0.002',
    'ratioStat': 1.795,
    'ratioStatType': {'id': 1183624559,
     'resource': 'Statistic Analysis',
     'synonyms': [],
     'term': 'OR',
     'termId': 'statAnalysis:1183624559',
     'valid': True},
    'statTests': [],
    'studyCases': 144,
    'studyControls': 105,
    'studyTypes': ['case/control', 'retrospective'],
    'usedForScoring': True}],
  'useForCaScoring': True},
 {'id': 699639147,
  'accessionId': 'PA166137273',
  'alleleGenotype': 'C',
  'comparison': 'T',
  'connWords1': {'id': 769229641,
   'resource': 'Phenotype Connecting words 1',
   'synonyms': [],
   'term': 'risk of',
   'termId': 'variantAnnotationPhenoConnWords1:769229641',
   'valid': True},
  'connWords2': {'id': 769229659,
   'resource': 'Phenotype or Gene to Drug Connecting Words',
   'synonyms': [],
   'term': 'when treated with',
   'termId': 'variantAnnotationPhenotypeConnWords2:769229659',
   'valid': True},
  'drugsConnWord': {'id': 827698395,
   'resource': 'Collection Operator - And/Or',
   'synonyms': [],
   'term': 'and',
   'termId': 'drugsConnWord:827698395',
   'valid': True},
  'formatVersion': 1,
  'history': [{'id': 1449761190,
    'date': '2018-11-05T14:07:03.812-08:00',
    'description': 'Updated OMB race to appropriate biogeographical group',
    'type': 'Update',
    'version': 0}],
  'isAssociated': True,
  'isPlural': False,
  'literature': {'id': 6462930,
   'title': 'Identification of genetic factors associated with susceptibility to angiotensin-converting enzyme inhibitors-induced cough.',
   '_sameAs': 'https://www.ncbi.nlm.nih.gov/pubmed/21052031',
   'authors': ['Grilo Antonio',
    'Sáez-Rosas María P',
    'Santos-Morano Juan',
    'Sánchez Elena',
    'Moreno-Rey Concha',
    'Real Luis M',
    'Ramírez-Lorca Reposo',
    'Sáez María E'],
   'crossReferences': [{'id': 699638774,
     'resource': 'PubMed',
     'resourceId': '21052031',
     '_url': 'https://www.ncbi.nlm.nih.gov/pubmed/21052031'},
    {'id': 1449245304,
     'resource': 'DOI',
     'resourceId': '10.1097/FPC.0b013e328341041c',
     '_url': 'http://dx.doi.org/10.1097%2FFPC.0b013e328341041c'}],
   'day': -1,
   'journal': 'Pharmacogenetics and genomics',
   'month': 1,
   'objCls': 'Literature',
   'page': '10-7',
   'pediatric': False,
   'pgkbPublication': False,
   'pubDate': '2011-01-01T00:00:00-08:00',
   'pubmedMeshTerms': [],
   'terms': [],
   'type': 'Literature',
   'volume': '21',
   'year': 2011},
  'location': {'id': 699639148,
   'buildVersion': 'hg19',
   'chromosomeId': 'PA503',
   'chromosomeName': 'chr1',
   'copyNumber': '1',
   'diplotypes': [],
   'displayName': 'rs11209716',
   'genes': [{'objCls': 'Gene',
     'id': 'PA288',
     'symbol': 'PTGER3',
     'name': 'prostaglandin E receptor 3'}],
   'gpPosition': 71377650,
   'haplotypes': [],
   'linkedObjects': [{'objCls': 'Variant',
     'id': 'PA166153821',
     'symbol': 'rs11209716',
     'name': 'rs11209716'}],
   'refSeqPosition': -1,
   'rsid': 'rs11209716',
   'tagGene': False,
   'type': 'SNP',
   'variant': {'objCls': 'Variant',
    'id': 'PA166153821',
    'symbol': 'rs11209716',
    'name': 'rs11209716'}},
  'metabolizers1': [],
  'metabolizers2': [],
  'objCls': 'Variant Phenotype Annotation',
  'pediatric': False,
  'phenotypeCategories': [{'id': 769229935,
    'resource': 'Phenotype Categories',
    'synonyms': [],
    'term': 'Toxicity',
    'termId': 'secondaryCat:769229935',
    'valid': True}],
  'phenotypes': [{'id': 94810434,
    'disease': {'objCls': 'Disease', 'id': 'PA443803', 'name': 'Cough'},
    'phenotype': 'Cough',
    'phenotypeContext': 'Disease'}],
  'polarity': {'id': 769229640,
   'resource': 'Polarity',
   'synonyms': [],
   'term': 'decreased',
   'termId': 'variantAnnotationPolarity:769229640',
   'valid': True},
  'populationPhenotypes': [{'id': 699639147,
    'disease': {'objCls': 'Disease', 'id': 'PA444552', 'name': 'Hypertension'},
    'phenotype': 'Hypertension',
    'phenotypeContext': 'Disease'}],
  'populationTerm': {'id': 769229662,
   'resource': 'Population',
   'synonyms': [],
   'term': 'in people with',
   'termId': 'variantAnnotationPhenotypeConnWords3:769229662',
   'valid': True},
  'relatedChemicals': [{'objCls': 'Chemical',
    'id': 'PA164712308',
    'name': 'Ace Inhibitors, Plain'}],
  'relatedVariations': [{'objCls': 'Allele',
    'id': 'PA166388104',
    'symbol': 'CA10808989',
    'name': 'NC_000001.11:g.70911967T>C'},
   {'objCls': 'Allele',
    'id': 'PA166388103',
    'symbol': 'CA1140249124',
    'name': 'NC_000001.11:g.70911967T='}],
  'score': 2.5,
  'scoreDetails': {'step5A': 1.0,
   'step5B': 1.0,
   'chosenSpId': 699639156,
   'step1Score': 1.0,
   'step2Score': 1.0,
   'step3Score': 0.5,
   'step4Score': 0.0,
   'totalScore': 2.5,
   'chosenSpIndex': '1 of 1',
   'generatedDate': '2021-03-20T21:33:09.066-07:00',
   'variantAnnotationId': 699639147},
  'sentence': 'Allele C is associated with decreased risk of Cough when treated with Ace Inhibitors, Plain in people with Hypertension as compared to allele T.',
  'sequenceLocation': {'id': 1447998518,
   'altHgvs': {},
   'assembly': 'GRCh37',
   'begin': 71377650,
   'end': 71377650,
   'intronicOffset': 0,
   'referenceAllele': 'T',
   'referenceHgvs': 'NC_000001.10:g.71377650=',
   'sequence': {'id': 1447949551,
    'name': '[GRCh37]chr1',
    'resource': 'RefSeq DNA',
    'resourceId': 'NC_000001.10',
    '_url': 'https://www.ncbi.nlm.nih.gov/nuccore/NC_000001.10'},
   'source': 'dbSnp',
   'type': 'genomic',
   'variantAlleles': ['C'],
   'variantHgvs': ['NC_000001.10:g.71377650T>C']},
  'significance': {'id': 769229666,
   'resource': 'Association Significance',
   'synonyms': [],
   'term': 'yes',
   'termId': 'variantAnnotationSignificance:769229666',
   'valid': True},
  'studyParameters': [{'id': 699639156,
    'characteristics': 'hypertension',
    'characteristicsType': 'Study Cohort',
    'confidenceIntervalStart': 0.39,
    'confidenceIntervalStop': 0.819,
    'frequencyInCases': -1.0,
    'frequencyInControls': -1.0,
    'pediatric': False,
    'populationEthnicity': {'custom': False,
     'ethnicities': [],
     'mixed': False,
     'notes': 'Spain',
     'unknown': True},
    'populationTypes': [],
    'pvalue': 0.002,
    'pvalueOp': {'id': 1183492001,
     'resource': 'Equality Symbols',
     'synonyms': [],
     'term': '=',
     'termId': 'equality:1183492001',
     'valid': True},
    'pvalueString': '0.002',
    'ratioStat': 0.565,
    'ratioStatType': {'id': 1183624559,
     'resource': 'Statistic Analysis',
     'synonyms': [],
     'term': 'OR',
     'termId': 'statAnalysis:1183624559',
     'valid': True},
    'statTests': [],
    'studyCases': 144,
    'studyControls': 105,
    'studyTypes': ['case/control', 'retrospective'],
    'usedForScoring': True}],
  'useForCaScoring': True},
 {'id': 699639202,
  'accessionId': 'PA166137349',
  'alleleGenotype': 'C',
  'comparison': 'T',
  'connWords1': {'id': 769229641,
   'resource': 'Phenotype Connecting words 1',
   'synonyms': [],
   'term': 'risk of',
   'termId': 'variantAnnotationPhenoConnWords1:769229641',
   'valid': True},
  'connWords2': {'id': 769229659,
   'resource': 'Phenotype or Gene to Drug Connecting Words',
   'synonyms': [],
   'term': 'when treated with',
   'termId': 'variantAnnotationPhenotypeConnWords2:769229659',
   'valid': True},
  'drugsConnWord': {'id': 827698395,
   'resource': 'Collection Operator - And/Or',
   'synonyms': [],
   'term': 'and',
   'termId': 'drugsConnWord:827698395',
   'valid': True},
  'formatVersion': 1,
  'history': [{'id': 1449760747,
    'date': '2018-11-05T14:04:53.463-08:00',
    'description': 'Updated OMB race to appropriate biogeographical group',
    'type': 'Update',
    'version': 0}],
  'isAssociated': True,
  'isPlural': False,
  'literature': {'id': 6462930,
   'title': 'Identification of genetic factors associated with susceptibility to angiotensin-converting enzyme inhibitors-induced cough.',
   '_sameAs': 'https://www.ncbi.nlm.nih.gov/pubmed/21052031',
   'authors': ['Grilo Antonio',
    'Sáez-Rosas María P',
    'Santos-Morano Juan',
    'Sánchez Elena',
    'Moreno-Rey Concha',
    'Real Luis M',
    'Ramírez-Lorca Reposo',
    'Sáez María E'],
   'crossReferences': [{'id': 699638774,
     'resource': 'PubMed',
     'resourceId': '21052031',
     '_url': 'https://www.ncbi.nlm.nih.gov/pubmed/21052031'},
    {'id': 1449245304,
     'resource': 'DOI',
     'resourceId': '10.1097/FPC.0b013e328341041c',
     '_url': 'http://dx.doi.org/10.1097%2FFPC.0b013e328341041c'}],
   'day': -1,
   'journal': 'Pharmacogenetics and genomics',
   'month': 1,
   'objCls': 'Literature',
   'page': '10-7',
   'pediatric': False,
   'pgkbPublication': False,
   'pubDate': '2011-01-01T00:00:00-08:00',
   'pubmedMeshTerms': [],
   'terms': [],
   'type': 'Literature',
   'volume': '21',
   'year': 2011},
  'location': {'id': 699639203,
   'buildVersion': 'hg19',
   'chromosomeId': 'PA512',
   'chromosomeName': 'chr14',
   'copyNumber': '1',
   'diplotypes': [],
   'displayName': 'rs8012552',
   'genes': [{'objCls': 'Gene',
     'id': 'PA80',
     'symbol': 'BDKRB2',
     'name': 'bradykinin receptor B2'}],
   'gpPosition': 96688767,
   'haplotypes': [],
   'linkedObjects': [{'objCls': 'Variant',
     'id': 'PA166154814',
     'symbol': 'rs8012552',
     'name': 'rs8012552'}],
   'refSeqPosition': -1,
   'rsid': 'rs8012552',
   'tagGene': False,
   'type': 'SNP',
   'variant': {'objCls': 'Variant',
    'id': 'PA166154814',
    'symbol': 'rs8012552',
    'name': 'rs8012552'}},
  'metabolizers1': [],
  'metabolizers2': [],
  'objCls': 'Variant Phenotype Annotation',
  'pediatric': False,
  'phenotypeCategories': [{'id': 769229935,
    'resource': 'Phenotype Categories',
    'synonyms': [],
    'term': 'Toxicity',
    'termId': 'secondaryCat:769229935',
    'valid': True}],
  'phenotypes': [{'id': 94810489,
    'disease': {'objCls': 'Disease', 'id': 'PA443803', 'name': 'Cough'},
    'phenotype': 'Cough',
    'phenotypeContext': 'Disease'}],
  'polarity': {'id': 769229639,
   'resource': 'Polarity',
   'synonyms': [],
   'term': 'increased',
   'termId': 'variantAnnotationPolarity:769229639',
   'valid': True},
  'populationPhenotypes': [{'id': 699639202,
    'disease': {'objCls': 'Disease', 'id': 'PA444552', 'name': 'Hypertension'},
    'phenotype': 'Hypertension',
    'phenotypeContext': 'Disease'}],
  'populationTerm': {'id': 769229662,
   'resource': 'Population',
   'synonyms': [],
   'term': 'in people with',
   'termId': 'variantAnnotationPhenotypeConnWords3:769229662',
   'valid': True},
  'relatedChemicals': [{'objCls': 'Chemical',
    'id': 'PA164712308',
    'name': 'Ace Inhibitors, Plain'}],
  'relatedVariations': [{'objCls': 'Allele',
    'id': 'PA166384863',
    'symbol': 'CA15815570',
    'name': 'NM_001379692.1(BDKRB2):c.-39-14639C>T'},
   {'objCls': 'Allele',
    'id': 'PA166384862',
    'symbol': 'CA2156824824',
    'name': 'NM_001379692.1(BDKRB2):c.-39-14639C='}],
  'score': 2.0,
  'scoreDetails': {'step5A': 1.0,
   'step5B': 1.0,
   'chosenSpId': 699639209,
   'step1Score': 1.0,
   'step2Score': 0.5,
   'step3Score': 0.5,
   'step4Score': 0.0,
   'totalScore': 2.0,
   'chosenSpIndex': '1 of 1',
   'generatedDate': '2021-03-20T21:33:25.381-07:00',
   'variantAnnotationId': 699639202},
  'sentence': 'Allele C is associated with increased risk of Cough when treated with Ace Inhibitors, Plain in people with Hypertension as compared to allele T.',
  'sequenceLocation': {'id': 1448019623,
   'altHgvs': {},
   'assembly': 'GRCh37',
   'begin': 96688767,
   'end': 96688767,
   'intronicOffset': 0,
   'referenceAllele': 'C',
   'referenceHgvs': 'NC_000014.8:g.96688767=',
   'sequence': {'id': 1447949564,
    'name': '[GRCh37]chr14',
    'resource': 'RefSeq DNA',
    'resourceId': 'NC_000014.8',
    '_url': 'https://www.ncbi.nlm.nih.gov/nuccore/NC_000014.8'},
   'source': 'dbSnp',
   'type': 'genomic',
   'variantAlleles': ['G', 'T'],
   'variantHgvs': ['NC_000014.8:g.96688767C>G', 'NC_000014.8:g.96688767C>T']},
  'significance': {'id': 769229666,
   'resource': 'Association Significance',
   'synonyms': [],
   'term': 'yes',
   'termId': 'variantAnnotationSignificance:769229666',
   'valid': True},
  'studyParameters': [{'id': 699639209,
    'characteristics': 'hypertension',
    'characteristicsType': 'Study Cohort',
    'confidenceIntervalStart': 1.107,
    'confidenceIntervalStop': 2.34,
    'frequencyInCases': -1.0,
    'frequencyInControls': -1.0,
    'pediatric': False,
    'populationEthnicity': {'custom': False,
     'ethnicities': [],
     'mixed': False,
     'notes': 'Spain',
     'unknown': True},
    'populationTypes': [],
    'pvalue': 0.012,
    'pvalueOp': {'id': 1183492001,
     'resource': 'Equality Symbols',
     'synonyms': [],
     'term': '=',
     'termId': 'equality:1183492001',
     'valid': True},
    'pvalueString': '0.012',
    'ratioStat': 1.609,
    'ratioStatType': {'id': 1183624559,
     'resource': 'Statistic Analysis',
     'synonyms': [],
     'term': 'OR',
     'termId': 'statAnalysis:1183624559',
     'valid': True},
    'statTests': [],
    'studyCases': 144,
    'studyControls': 105,
    'studyTypes': ['case/control', 'retrospective'],
    'usedForScoring': True}],
  'useForCaScoring': True},
 {'id': 769169226,
  'accessionId': 'PA166137649',
  'alleleGenotype': 'GG',
  'connWords1': {'id': 769229641,
   'resource': 'Phenotype Connecting words 1',
   'synonyms': [],
   'term': 'risk of',
   'termId': 'variantAnnotationPhenoConnWords1:769229641',
   'valid': True},
  'connWords2': {'id': 769229659,
   'resource': 'Phenotype or Gene to Drug Connecting Words',
   'synonyms': [],
   'term': 'when treated with',
   'termId': 'variantAnnotationPhenotypeConnWords2:769229659',
   'valid': True},

##### Creating a Pandas dataframe from the dictionary

The next setp is to create a dataframe from the dictionary. For our purposes, the dictionary was opened up at the second level of nested information since the data on display is more relevant.

In [24]:
drug_df = pd.DataFrame.from_records(data['data']) #using the found key to put this nested data from within the dict into a dataframe

###### Displaying the dataframe

The newly created dataframe is displayed, allowing for the easy viewing of the data.

In [26]:
(drug_df)

,id,accessionId,alleleGenotype,comparison,connWords1,connWords2,drugsConnWord,formatVersion,history,isAssociated,...,scoreDetails,sentence,sequenceLocation,significance,studyParameters,useForCaScoring,description,phenotypeLinksConnWord,populationPhenotypeLinksConnWord,scoringRationale
0,699639186,PA166137232,A,G,"{'id': 769229641, 'resource': 'Phenotype Conne...","{'id': 769229659, 'resource': 'Phenotype or Ge...","{'id': 827698395, 'resource': 'Collection Oper...",1,"[{'id': 1449761119, 'date': '2018-11-05T14:06:...",True,...,"{'step5A': 1.0, 'step5B': 1.0, 'chosenSpId': 6...",Allele A is associated with increased risk of ...,"{'id': 1448059186, 'altHgvs': {}, 'assembly': ...","{'id': 769229666, 'resource': 'Association Sig...","[{'id': 699639198, 'characteristics': 'hyperte...",True,NaN,NaN,NaN,NaN
1,699639147,PA166137273,C,T,"{'id': 769229641, 'resource': 'Phenotype Conne...","{'id': 769229659, 'resource': 'Phenotype or Ge...","{'id': 827698395, 'resource': 'Collection Oper...",1,"[{'id': 1449761190, 'date': '2018-11-05T14:07:...",True,...,"{'step5A': 1.0, 'step5B': 1.0, 'chosenSpId': 6...",Allele C is associated with decreased risk of ...,"{'id': 1447998518, 'altHgvs': {}, 'assembly': ...","{'id': 769229666, 'resource': 'Association Sig...","[{'id': 699639156, 'characteristics': 'hyperte...",True,NaN,NaN,NaN,NaN
2,699639202,PA166137349,C,T,"{'id': 769229641, 'resource': 'Phenotype Conne...","{'id': 769229659, 'resource': 'Phenotype or Ge...","{'id': 827698395, 'resource': 'Collection Oper...",1,"[{'id': 1449760747, 'date': '2018-11-05T14:04:...",True,...,"{'step5A': 1.0, 'step5B': 1.0, 'chosenSpId': 6...",Allele C is associated with increased risk of ...,"{'id': 1448019623, 'altHgvs': {}, 'assembly': ...","{'id': 769229666, 'resource': 'Association Sig...","[{'id': 699639209, 'characteristics': 'hyperte...",True,NaN,NaN,NaN,NaN
3,769169226,PA166137649,GG,NaN,"{'id': 769229641, 'resource': 'Phenotype Conne...","{'id': 769229659, 'resource': 'Phenotype or Ge...","{'id': 827698395, 'resource': 'Collection Oper...",1,"[{'id': 1449762972, 'date': '2018-11-05T14:16:...",True,...,"{'step5A': 1.0, 'step5B': 1.0, 'chosenSpId': 7...",Genotype GG is associated with decreased risk ...,"{'id': 1447992491, 'altHgvs': {}, 'assembly': ...","{'id': 769229666, 'resource': 'Association Sig...","[{'id': 769169241, 'characteristics': 'HMO mem...",True,Non-fatal stroke was assessed. Comparison is ...,NaN,NaN,NaN
4,769169242,PA166137557,GG,NaN,"{'id': 769229641, 'resource': 'Phenotype Conne...","{'id': 769229659, 'resource': 'Phenotype or Ge...","{'id': 827698395, 'resource': 'Collection Oper...",1,"[{'id': 1449762997, 'date': '2018-11-05T14:16:...",False,...,"{'step5A': 1.0, 'step5B': -1.0, 'chosenSpId': ...",Genotype GG is not associated with decreased r...,"{'id': 1447992491, 'altHgvs': {}, 'assembly': ...","{'id': 769229667, 'resource': 'Association Sig...","[{'id': 769169244, 'characteristics': 'HMO mem...",True,Non-fatal MI was assessed.,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,1451355885,PA166232827,AT,NaN,"{'id': 769229641, 'resource': 'Phenotype Conne...","{'id': 769229659, 'resource': 'Phenotype or Ge...","{'id': 827698396, 'resource': 'Collection Oper...",2,"[{'id': 1451355889, 'date': '2021-03-16T11:20:...",False,...,"{'step5A': 1.0, 'step5B': -1.0, 'chosenSpId': ...",Genotype AT is not associated with increased r...,"{'id': 1451355798, 'altHgvs': {}, 'assembly': ...","{'id': 769229667, 'resource': 'Association Sig...","[{'id': 1451355890, 'characteristics': '23% of...",True,NaN,NaN,NaN,NaN
72,1451355907,PA166232882,CG,NaN,"{'id': 769229641, 'resource': 'Phenotype Conne...","{'id': 769229659, 'resource': 'Phenotype or Ge...","{'id': 827698396, 'resource': 'Collection Oper...",2,"[{'id': 1451355911, 'date': '2021-03-16T11:24:...",False,...,"{'step5A': 1.0, 'step5B': -1.0, 'chosenSpId': ...",Genotype CG is not associated with increased r...,"{'id': 1451355900, 'altHgvs': {}, 'assembly': ...","{'id': 769229667, 'resource': 'Association Sig...","[{'id': 1451355920, 'characteristics': '23% of...",True,NaN,NaN,NaN,NaN
73,1451355927,PA166232902,CT,NaN,"{'id': 769229641, 'resource': 'Phenotype Conne...","{'id': 769229659, 'resource': 'Phenotype or Ge...","{'id': 827698396, 'resource': 'Collection Oper...",2,"[{'id': 1451355931, 'date': '2021-03-16T11:26:...",True,...,"{'step5A': 1.0, 'step5B': 0.0, 'chosenSpId': 1...",Genotype CT is associated with increased risk ...,"{'id': 1451355921, 'altHgvs': {}, 'assembly': ...","{'id': 769229666, 'resource': 'Association Sig...","[{'id': 1451355940, 'characteristics': '23% of...",True,NaN,NaN,NaN,NaN
74,1451356020,PA166232941,AG,NaN,"{'id': 769229641, 'resource': 'Phenotype Conne...","{'id': 769229659, 'resource': 'Phenotype or Ge...","{'id': 827698396, 'resource': 'Collection Oper...",2,"[{'id': 1451356024, 'date': '2021-03-16T11:30:...",True,...,"{'step5A': 1.0, 'step5B': 0.0, 'chosenSpId': 1...",Genotype AG is associated with increased risk ...,"{'id': 1451355980, 'altHgvs': {}, 'assembly': ...","{'id': 769229666, 'resource': 'Association Sig...","[{'id': 1451355985, 'characteristics': '23% of...",True,NaN,NaN,NaN,NaN
75,1451411160,PA166238541,G,A,"{'id': 769229641, 'resource': 'Phenotype Conne...","{'id': 769229659, 'resource': 'Phenotype or Ge...",NaN,2,"[{'id': 1451411164, 'date': '2021-04-14T15:07:...",True,...,"{'step5A': 1.0, 'step5B': 1.0, 'chosenSpId': 1...",Allele G is associated with increased risk of ...,"{'id': 1451411120, 'altHgvs': {}, 'assembly': ...","{'id': 769229666, 'resource': 'Association Sig...","[{'id': 1451411165, 'characteristics': 'Discov...",True,This was a significant association in the disc...,NaN,NaN,NaN

##### Columns within the dataframe

The names of each of the columns within the new dataframe is printed.

In [28]:
drug_df.columns #printing the columns in the dataframe

Index(['id', 'accessionId', 'alleleGenotype', 'comparison', 'connWords1',
       'connWords2', 'drugsConnWord', 'formatVersion', 'history',
       'isAssociated', 'isPlural', 'literature', 'location', 'metabolizers1',
       'metabolizers2', 'objCls', 'pediatric', 'phenotypeCategories',
       'phenotypes', 'polarity', 'populationPhenotypes', 'populationTerm',
       'relatedChemicals', 'relatedVariations', 'score', 'scoreDetails',
       'sentence', 'sequenceLocation', 'significance', 'studyParameters',
       'useForCaScoring', 'description', 'phenotypeLinksConnWord',
       'populationPhenotypeLinksConnWord', 'scoringRationale'],
      dtype='object')

##### Column names are loaded into a list

In order to only display data that is relevant, the names of columns that are to be included were loaded into a list.

In [30]:
 cols= [ #listing only the columns that I want to see
       'description',
       'isAssociated', 'score', 'sentence',
       'sequenceLocation', 'literature']

##### Modifying the dataframe

The next step is modifying the existing dataframe to only include columns that was included in the newly made list.

In [32]:
drug_df = drug_df[cols] #now the dataframe will only show columns with information that is wanted
#overwritting this to consider this as the base drug_df

##### Displaying the newly modified dataframe

This is to display the modified dataframe. Next, the nested information within this level will be opened up and saved in order to display the desired information.

In [34]:
drug_df

,description,isAssociated,score,sentence,sequenceLocation,literature
0,NaN,True,2.5,Allele A is associated with increased risk of ...,"{'id': 1448059186, 'altHgvs': {}, 'assembly': ...","{'id': 6462930, 'title': 'Identification of ge..."
1,NaN,True,2.5,Allele C is associated with decreased risk of ...,"{'id': 1447998518, 'altHgvs': {}, 'assembly': ...","{'id': 6462930, 'title': 'Identification of ge..."
2,NaN,True,2.0,Allele C is associated with increased risk of ...,"{'id': 1448019623, 'altHgvs': {}, 'assembly': ...","{'id': 6462930, 'title': 'Identification of ge..."
3,Non-fatal stroke was assessed. Comparison is ...,True,2.0,Genotype GG is associated with decreased risk ...,"{'id': 1447992491, 'altHgvs': {}, 'assembly': ...","{'id': 6372035, 'title': 'Angiotensinogen Met2..."
4,Non-fatal MI was assessed.,False,-2.0,Genotype GG is not associated with decreased r...,"{'id': 1447992491, 'altHgvs': {}, 'assembly': ...","{'id': 6372035, 'title': 'Angiotensinogen Met2..."
...,...,...,...,...,...,...
71,NaN,False,-2.0,Genotype AT is not associated with increased r...,"{'id': 1451355798, 'altHgvs': {}, 'assembly': ...","{'id': 15116562, 'title': 'Exome Sequencing Re..."
72,NaN,False,-2.0,Genotype CG is not associated with increased r...,"{'id': 1451355900, 'altHgvs': {}, 'assembly': ...","{'id': 15116562, 'title': 'Exome Sequencing Re..."
73,NaN,True,0.0,Genotype CT is associated with increased risk ...,"{'id': 1451355921, 'altHgvs': {}, 'assembly': ...","{'id': 15116562, 'title': 'Exome Sequencing Re..."
74,NaN,True,0.0,Genotype AG is associated with increased risk ...,"{'id': 1451355980, 'altHgvs': {}, 'assembly': ...","{'id': 15116562, 'title': 'Exome Sequencing Re..."
75,This was a significant association in the disc...,True,3.0,Allele G is associated with increased risk of ...,"{'id': 1451411120, 'altHgvs': {}, 'assembly': ...","{'id': 15119262, 'title': 'Genome-wide associa..."

##### Opening up the nested information within a column of the dataframe

This will be done by extracting nested data from a specified column of the dataframe, this time we are doing sequenceLocation, and then creating a new dataframe from it.

In [36]:
seqlocation_df = pd.DataFrame.from_records(drug_df['sequenceLocation']) #using the found key to put this nested data from within the dict into a dataframe

##### Displaying the new dataframe made from the column of the original dataframe

This will allow us to open up this level of nested information, easily navigate the information, and choose what data is desired.

In [38]:
seqlocation_df

,id,altHgvs,assembly,begin,end,intronicOffset,referenceAllele,referenceHgvs,sequence,source,type,variantAlleles,variantHgvs,notes
0,1448059186,{},GRCh37,154858685,154858685,0,G,NC_000003.11:g.154858685=,"{'id': 1447949553, 'name': '[GRCh37]chr3', 're...",dbSnp,genomic,"[A, C, T]","[NC_000003.11:g.154858685G>A, NC_000003.11:g.1...",NaN
1,1447998518,{},GRCh37,71377650,71377650,0,T,NC_000001.10:g.71377650=,"{'id': 1447949551, 'name': '[GRCh37]chr1', 're...",dbSnp,genomic,[C],[NC_000001.10:g.71377650T>C],NaN
2,1448019623,{},GRCh37,96688767,96688767,0,C,NC_000014.8:g.96688767=,"{'id': 1447949564, 'name': '[GRCh37]chr14', 'r...",dbSnp,genomic,"[G, T]","[NC_000014.8:g.96688767C>G, NC_000014.8:g.9668...",NaN
3,1447992491,{},GRCh37,230845794,230845794,0,A,NC_000001.10:g.230845794=,"{'id': 1447949551, 'name': '[GRCh37]chr1', 're...",dbSnp,genomic,[G],[NC_000001.10:g.230845794A>G],NaN
4,1447992491,{},GRCh37,230845794,230845794,0,A,NC_000001.10:g.230845794=,"{'id': 1447949551, 'name': '[GRCh37]chr1', 're...",dbSnp,genomic,[G],[NC_000001.10:g.230845794A>G],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,1451355798,{},GRCh38,169542347,169542347,0,T,NC_000001.11:g.169542347=,"{'id': 1445125164, 'name': '[GRCh38]chr1', 're...",dbSnp,genomic,[A],[NC_000001.11:g.169542347T>A],NaN
72,1451355900,{},GRCh38,169572275,169572275,0,C,NC_000001.11:g.169572275=,"{'id': 1445125164, 'name': '[GRCh38]chr1', 're...",dbSnp,genomic,"[G, T]","[NC_000001.11:g.169572275C>G, NC_000001.11:g.1...",NaN
73,1451355921,{},GRCh38,169544331,169544331,0,C,NC_000001.11:g.169544331=,"{'id': 1445125164, 'name': '[GRCh38]chr1', 're...",dbSnp,genomic,[T],[NC_000001.11:g.169544331C>T],NaN
74,1451355980,{},GRCh38,169529903,169529903,0,A,NC_000001.11:g.169529903=,"{'id': 1445125164, 'name': '[GRCh38]chr1', 're...",dbSnp,genomic,[G],[NC_000001.11:g.169529903A>G],NaN
75,1451411120,{},GRCh38,77596639,77596639,0,G,NC_000010.11:g.77596639=,"{'id': 1446906616, 'name': '[GRCh38]chr10', 'r...",dbSnp,genomic,"[A, C]","[NC_000010.11:g.77596639G>A, NC_000010.11:g.77...",NaN

##### Displaying only the column that is desired

The desired column within this dataframe will be selected for further manipulation.

In [40]:
seqlocation_df['variantHgvs'] #displaying the column within the seqlocation that I actually want to see

0     [NC_000003.11:g.154858685G>A, NC_000003.11:g.1...
1                          [NC_000001.10:g.71377650T>C]
2     [NC_000014.8:g.96688767C>G, NC_000014.8:g.9668...
3                         [NC_000001.10:g.230845794A>G]
4                         [NC_000001.10:g.230845794A>G]
                            ...
71                        [NC_000001.11:g.169542347T>A]
72    [NC_000001.11:g.169572275C>G, NC_000001.11:g.1...
73                        [NC_000001.11:g.169544331C>T]
74                        [NC_000001.11:g.169529903A>G]
75    [NC_000010.11:g.77596639G>A, NC_000010.11:g.77...
Name: variantHgvs, Length: 76, dtype: object

##### Modifying the original dataframe

This will trasnform the data from the specified column into the original dataframe. Now the original dataframe will only display the desired information from within the nested information. Next step would be doing the same processs to the other nested information within the dataframe so that all the desired information is easily viewed and digestable

In [42]:
seqlocation_df = pd.DataFrame.from_records(drug_df['sequenceLocation']) #using the found key to put this nested data from within the dict into a dataframe

In [43]:
seqlocation_df #printing the new df with the changes to the column and the displayed nested data

,id,altHgvs,assembly,begin,end,intronicOffset,referenceAllele,referenceHgvs,sequence,source,type,variantAlleles,variantHgvs,notes
0,1448059186,{},GRCh37,154858685,154858685,0,G,NC_000003.11:g.154858685=,"{'id': 1447949553, 'name': '[GRCh37]chr3', 're...",dbSnp,genomic,"[A, C, T]","[NC_000003.11:g.154858685G>A, NC_000003.11:g.1...",NaN
1,1447998518,{},GRCh37,71377650,71377650,0,T,NC_000001.10:g.71377650=,"{'id': 1447949551, 'name': '[GRCh37]chr1', 're...",dbSnp,genomic,[C],[NC_000001.10:g.71377650T>C],NaN
2,1448019623,{},GRCh37,96688767,96688767,0,C,NC_000014.8:g.96688767=,"{'id': 1447949564, 'name': '[GRCh37]chr14', 'r...",dbSnp,genomic,"[G, T]","[NC_000014.8:g.96688767C>G, NC_000014.8:g.9668...",NaN
3,1447992491,{},GRCh37,230845794,230845794,0,A,NC_000001.10:g.230845794=,"{'id': 1447949551, 'name': '[GRCh37]chr1', 're...",dbSnp,genomic,[G],[NC_000001.10:g.230845794A>G],NaN
4,1447992491,{},GRCh37,230845794,230845794,0,A,NC_000001.10:g.230845794=,"{'id': 1447949551, 'name': '[GRCh37]chr1', 're...",dbSnp,genomic,[G],[NC_000001.10:g.230845794A>G],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,1451355798,{},GRCh38,169542347,169542347,0,T,NC_000001.11:g.169542347=,"{'id': 1445125164, 'name': '[GRCh38]chr1', 're...",dbSnp,genomic,[A],[NC_000001.11:g.169542347T>A],NaN
72,1451355900,{},GRCh38,169572275,169572275,0,C,NC_000001.11:g.169572275=,"{'id': 1445125164, 'name': '[GRCh38]chr1', 're...",dbSnp,genomic,"[G, T]","[NC_000001.11:g.169572275C>G, NC_000001.11:g.1...",NaN
73,1451355921,{},GRCh38,169544331,169544331,0,C,NC_000001.11:g.169544331=,"{'id': 1445125164, 'name': '[GRCh38]chr1', 're...",dbSnp,genomic,[T],[NC_000001.11:g.169544331C>T],NaN
74,1451355980,{},GRCh38,169529903,169529903,0,A,NC_000001.11:g.169529903=,"{'id': 1445125164, 'name': '[GRCh38]chr1', 're...",dbSnp,genomic,[G],[NC_000001.11:g.169529903A>G],NaN
75,1451411120,{},GRCh38,77596639,77596639,0,G,NC_000010.11:g.77596639=,"{'id': 1446906616, 'name': '[GRCh38]chr10', 'r...",dbSnp,genomic,"[A, C]","[NC_000010.11:g.77596639G>A, NC_000010.11:g.77...",NaN

##### Creating a function

Creating a function, parsePharmGKB. This function will open the PharmGKB file, loading the file into a dict, then using the found keys to pull the nested data from within the dict intoa dactaframe to return a dataframe that only shows columns with relevant information.

In [45]:
def parsePharmGKB(file, dgkbdf):
  with open(file, 'r') as file: #opening PharmGKB file
    data = json.load(file) #loading the file data into a dict
  dgkbdf = pd.DataFrame.from_records(data['data']) #using the found key to put this nested data from within the dict into a dataframe
  cols= [ #listing only the columns that I want to see
       'description',
       'isAssociated', 'score', 'sentence',
       'sequenceLocation']
  return dgkbdf[cols] #now the dataframe will only show columns with information that is wanted

parsePharmGKB('C:/Users/ian/downloads/pharmGKBdata.json', 'parsedGKB') #condensing the last steps into a function

,description,isAssociated,score,sentence,sequenceLocation
0,NaN,True,2.5,Allele A is associated with increased risk of ...,"{'id': 1448059186, 'altHgvs': {}, 'assembly': ..."
1,NaN,True,2.5,Allele C is associated with decreased risk of ...,"{'id': 1447998518, 'altHgvs': {}, 'assembly': ..."
2,NaN,True,2.0,Allele C is associated with increased risk of ...,"{'id': 1448019623, 'altHgvs': {}, 'assembly': ..."
3,Non-fatal stroke was assessed. Comparison is ...,True,2.0,Genotype GG is associated with decreased risk ...,"{'id': 1447992491, 'altHgvs': {}, 'assembly': ..."
4,Non-fatal MI was assessed.,False,-2.0,Genotype GG is not associated with decreased r...,"{'id': 1447992491, 'altHgvs': {}, 'assembly': ..."
...,...,...,...,...,...
71,NaN,False,-2.0,Genotype AT is not associated with increased r...,"{'id': 1451355798, 'altHgvs': {}, 'assembly': ..."
72,NaN,False,-2.0,Genotype CG is not associated with increased r...,"{'id': 1451355900, 'altHgvs': {}, 'assembly': ..."
73,NaN,True,0.0,Genotype CT is associated with increased risk ...,"{'id': 1451355921, 'altHgvs': {}, 'assembly': ..."
74,NaN,True,0.0,Genotype AG is associated with increased risk ...,"{'id': 1451355980, 'altHgvs': {}, 'assembly': ..."
75,This was a significant association in the disc...,True,3.0,Allele G is associated with increased risk of ...,"{'id': 1451411120, 'altHgvs': {}, 'assembly': ..."

### Parsing DGIdb

For DGIdb, the columns we are looking to extract are the gene name, the ID, the long name and its interaction score. This helps us identify targetable genes for drug repurposing and links genetic data to available theraputics.

In [47]:
with open('C:/Users/ian/downloads/DGIdbdata.json', 'r') as file: #opening DGIdbdata file
    data = json.load(file) #loading the file data into a dict
keys = data.keys() #getting the dict keys
print(keys)

dict_keys(['data'])

In [48]:
data #opening the raw data dict

{'data': {'drugs': {'nodes': [{'interactions': [{'gene': {'name': 'HTR1B',
        'conceptId': 'hgnc:5287',
        'longName': '5-hydroxytryptamine receptor 1B'},
       'interactionScore': 1.535405839967221,
       'interactionTypes': [],
       'interactionAttributes': [],
       'publications': [],
       'sources': [{'sourceDbName': 'TTD'}]}]},
    {'interactions': [{'gene': {'name': 'IL7',
        'conceptId': 'hgnc:6023',
        'longName': 'interleukin 7'},
       'interactionScore': 1.933474020699464,
       'interactionTypes': [],
       'interactionAttributes': [],
       'publications': [{'pmid': 17215438}],
       'sources': [{'sourceDbName': 'NCI'}]},
      {'gene': {'name': 'GGT1',
        'conceptId': 'hgnc:4250',
        'longName': 'gamma-glutamyltransferase 1'},
       'interactionScore': 0.4296608934887697,
       'interactionTypes': [],
       'interactionAttributes': [],
       'publications': [{'pmid': 8443268}],
       'sources': [{'sourceDbName': 'NCI'}]},
      {'gene': {'name': 'GHRL',
        'conceptId': 'hgnc:18129',
        'longName': 'ghrelin and obestatin prepropeptide'},
       'interactionScore': 0.6824025955409873,
       'interactionTypes': [],
       'interactionAttributes': [],
       'publications': [{'pmid': 18197141}],
       'sources': [{'sourceDbName': 'NCI'}]},
      {'gene': {'name': 'MPO',
        'conceptId': 'hgnc:7218',
        'longName': 'myeloperoxidase'},
       'interactionScore': 0.5800422062098393,
       'interactionTypes': [],
       'interactionAttributes': [],
       'publications': [{'pmid': 12969831}, {'pmid': 10522845}],
       'sources': [{'sourceDbName': 'NCI'}]},
      {'gene': {'name': 'CDX2',
        'conceptId': 'hgnc:1806',
        'longName': 'caudal type homeobox 2'},
       'interactionScore': 3.866948041398928,
       'interactionTypes': [],
       'interactionAttributes': [],
       'publications': [{'pmid': 10712262}],
       'sources': [{'sourceDbName': 'NCI'}]},
      {'gene': {'name': 'IL1B',
        'conceptId': 'hgnc:5992',
        'longName': 'interleukin 1 beta'},
       'interactionScore': 0.2274675318469957,
       'interactionTypes': [],
       'interactionAttributes': [],
       'publications': [{'pmid': 8724378}],
       'sources': [{'sourceDbName': 'NCI'}]},
      {'gene': {'name': 'TYMS',
        'conceptId': 'hgnc:12441',
        'longName': 'thymidylate synthetase'},
       'interactionScore': 0.2367519209019752,
       'interactionTypes': [],
       'interactionAttributes': [],
       'publications': [{'pmid': 7790321}],
       'sources': [{'sourceDbName': 'NCI'}]},
      {'gene': {'name': 'IL2RA',
        'conceptId': 'hgnc:6008',
        'longName': 'interleukin 2 receptor subunit alpha'},
       'interactionScore': 0.2274675318469957,
       'interactionTypes': [],
       'interactionAttributes': [],
       'publications': [{'pmid': 11895146}],
       'sources': [{'sourceDbName': 'NCI'}]},
      {'gene': {'name': 'MYC',
        'conceptId': 'hgnc:7553',
        'longName': 'MYC proto-oncogene, bHLH transcription factor'},
       'interactionScore': 0.1657263446313826,
       'interactionTypes': [],
       'interactionAttributes': [],
       'publications': [{'pmid': 12005453}],
       'sources': [{'sourceDbName': 'NCI'}]}]},
    {'interactions': [{'gene': {'name': 'G6PD',
        'conceptId': 'hgnc:4057',
        'longName': 'glucose-6-phosphate dehydrogenase'},
       'interactionScore': 0.5220379855888554,
       'interactionTypes': [],
       'interactionAttributes': [],
       'publications': [],
       'sources': [{'sourceDbName': 'PharmGKB'}]}]},
    {'interactions': []}]}}}

In [49]:
data['data']['drugs']['nodes'] #opening in nested keys

[{'interactions': [{'gene': {'name': 'HTR1B',
     'conceptId': 'hgnc:5287',
     'longName': '5-hydroxytryptamine receptor 1B'},
    'interactionScore': 1.535405839967221,
    'interactionTypes': [],
    'interactionAttributes': [],
    'publications': [],
    'sources': [{'sourceDbName': 'TTD'}]}]},
 {'interactions': [{'gene': {'name': 'IL7',
     'conceptId': 'hgnc:6023',
     'longName': 'interleukin 7'},
    'interactionScore': 1.933474020699464,
    'interactionTypes': [],
    'interactionAttributes': [],
    'publications': [{'pmid': 17215438}],
    'sources': [{'sourceDbName': 'NCI'}]},
   {'gene': {'name': 'GGT1',
     'conceptId': 'hgnc:4250',
     'longName': 'gamma-glutamyltransferase 1'},
    'interactionScore': 0.4296608934887697,
    'interactionTypes': [],
    'interactionAttributes': [],
    'publications': [{'pmid': 8443268}],
    'sources': [{'sourceDbName': 'NCI'}]},
   {'gene': {'name': 'GHRL',
     'conceptId': 'hgnc:18129',
     'longName': 'ghrelin and obestatin prepropeptide'},
    'interactionScore': 0.6824025955409873,
    'interactionTypes': [],
    'interactionAttributes': [],
    'publications': [{'pmid': 18197141}],
    'sources': [{'sourceDbName': 'NCI'}]},
   {'gene': {'name': 'MPO',
     'conceptId': 'hgnc:7218',
     'longName': 'myeloperoxidase'},
    'interactionScore': 0.5800422062098393,
    'interactionTypes': [],
    'interactionAttributes': [],
    'publications': [{'pmid': 12969831}, {'pmid': 10522845}],
    'sources': [{'sourceDbName': 'NCI'}]},
   {'gene': {'name': 'CDX2',
     'conceptId': 'hgnc:1806',
     'longName': 'caudal type homeobox 2'},
    'interactionScore': 3.866948041398928,
    'interactionTypes': [],
    'interactionAttributes': [],
    'publications': [{'pmid': 10712262}],
    'sources': [{'sourceDbName': 'NCI'}]},
   {'gene': {'name': 'IL1B',
     'conceptId': 'hgnc:5992',
     'longName': 'interleukin 1 beta'},
    'interactionScore': 0.2274675318469957,
    'interactionTypes': [],
    'interactionAttributes': [],
    'publications': [{'pmid': 8724378}],
    'sources': [{'sourceDbName': 'NCI'}]},
   {'gene': {'name': 'TYMS',
     'conceptId': 'hgnc:12441',
     'longName': 'thymidylate synthetase'},
    'interactionScore': 0.2367519209019752,
    'interactionTypes': [],
    'interactionAttributes': [],
    'publications': [{'pmid': 7790321}],
    'sources': [{'sourceDbName': 'NCI'}]},
   {'gene': {'name': 'IL2RA',
     'conceptId': 'hgnc:6008',
     'longName': 'interleukin 2 receptor subunit alpha'},
    'interactionScore': 0.2274675318469957,
    'interactionTypes': [],
    'interactionAttributes': [],
    'publications': [{'pmid': 11895146}],
    'sources': [{'sourceDbName': 'NCI'}]},
   {'gene': {'name': 'MYC',
     'conceptId': 'hgnc:7553',
     'longName': 'MYC proto-oncogene, bHLH transcription factor'},
    'interactionScore': 0.1657263446313826,
    'interactionTypes': [],
    'interactionAttributes': [],
    'publications': [{'pmid': 12005453}],
    'sources': [{'sourceDbName': 'NCI'}]}]},
 {'interactions': [{'gene': {'name': 'G6PD',
     'conceptId': 'hgnc:4057',
     'longName': 'glucose-6-phosphate dehydrogenase'},
    'interactionScore': 0.5220379855888554,
    'interactionTypes': [],
    'interactionAttributes': [],
    'publications': [],
    'sources': [{'sourceDbName': 'PharmGKB'}]}]},
 {'interactions': []}]

In [50]:
drug_df = pd.DataFrame.from_records(data['data']['drugs']['nodes']) #using the found key to pulll this nested data from within the dict into a dataframe
(drug_df)

#ideally looking to display the gene names, the long names, interaction scores

                                        interactions
0  [{'gene': {'name': 'HTR1B', 'conceptId': 'hgnc...
1  [{'gene': {'name': 'IL7', 'conceptId': 'hgnc:6...
2  [{'gene': {'name': 'G6PD', 'conceptId': 'hgnc:...
3                                                 []

In [51]:
drug_df.columns #printing the columns in the dataframe

Index(['interactions'], dtype='object')

In [52]:
#extracting the drug interaction nodes
drug_nodes = data['data']['drugs']['nodes']

#creating a list to hold flat records
records = []

#working through the nested structure
for drug_idx, drug in enumerate(drug_nodes):
    for interaction in drug.get('interactions', []):
        gene = interaction.get('gene', {})
        interaction_score = interaction.get('interactionScore')
        pmids = [pub.get('pmid') for pub in interaction.get('publications', [])]
        sources = [source.get('sourceDbName') for source in interaction.get('sources', [])]

        records.append({
            'drug_index': drug_idx,
            'gene_name': gene.get('name'),
            'concept_id': gene.get('conceptId'),
            'gene_long_name': gene.get('longName'),
            'interaction_score': interaction_score,
            'pmids': ', '.join(map(str, pmids)) if pmids else None,
            'sources': ', '.join(sources) if sources else None
        })

df = pd.DataFrame(records) #creating the dataframe

df #displaying the dataframe

,drug_index,gene_name,concept_id,gene_long_name,interaction_score,pmids,sources
0,0,HTR1B,hgnc:5287,5-hydroxytryptamine receptor 1B,1.535406,None,TTD
1,1,IL7,hgnc:6023,interleukin 7,1.933474,17215438,NCI
2,1,GGT1,hgnc:4250,gamma-glutamyltransferase 1,0.429661,8443268,NCI
3,1,GHRL,hgnc:18129,ghrelin and obestatin prepropeptide,0.682403,18197141,NCI
4,1,MPO,hgnc:7218,myeloperoxidase,0.580042,"12969831, 10522845",NCI
5,1,CDX2,hgnc:1806,caudal type homeobox 2,3.866948,10712262,NCI
6,1,IL1B,hgnc:5992,interleukin 1 beta,0.227468,8724378,NCI
7,1,TYMS,hgnc:12441,thymidylate synthetase,0.236752,7790321,NCI
8,1,IL2RA,hgnc:6008,interleukin 2 receptor subunit alpha,0.227468,11895146,NCI
9,1,MYC,hgnc:7553,"MYC proto-oncogene, bHLH transcription factor",0.165726,12005453,NCI
10,2,G6PD,hgnc:4057,glucose-6-phosphate dehydrogenase,0.522038,None,PharmGKB

##### Creating a function

In [54]:
def extract_interactions_to_df(data):
    drug_nodes = data['data']['drugs']['nodes']
    records = []

    for drug_idx, drug in enumerate(drug_nodes):
        for interaction in drug.get('interactions', []):
            gene = interaction.get('gene', {})
            interaction_score = interaction.get('interactionScore')
            pmids = [pub.get('pmid') for pub in interaction.get('publications', [])]
            sources = [src.get('sourceDbName') for src in interaction.get('sources', [])]

            records.append({
                'drug_index': drug_idx,
                'gene_name': gene.get('name'),
                'concept_id': gene.get('conceptId'),
                'gene_long_name': gene.get('longName'),
                'interaction_score': interaction_score,
                'pmids': ', '.join(map(str, pmids)) if pmids else None,
                'sources': ', '.join(sources) if sources else None
            })

    return pd.DataFrame(records)
#creating a function to pull information from DGIdb

In [55]:
extract_interactions_to_df(data) #testing the new function for DGIdb

,drug_index,gene_name,concept_id,gene_long_name,interaction_score,pmids,sources
0,0,HTR1B,hgnc:5287,5-hydroxytryptamine receptor 1B,1.535406,None,TTD
1,1,IL7,hgnc:6023,interleukin 7,1.933474,17215438,NCI
2,1,GGT1,hgnc:4250,gamma-glutamyltransferase 1,0.429661,8443268,NCI
3,1,GHRL,hgnc:18129,ghrelin and obestatin prepropeptide,0.682403,18197141,NCI
4,1,MPO,hgnc:7218,myeloperoxidase,0.580042,"12969831, 10522845",NCI
5,1,CDX2,hgnc:1806,caudal type homeobox 2,3.866948,10712262,NCI
6,1,IL1B,hgnc:5992,interleukin 1 beta,0.227468,8724378,NCI
7,1,TYMS,hgnc:12441,thymidylate synthetase,0.236752,7790321,NCI
8,1,IL2RA,hgnc:6008,interleukin 2 receptor subunit alpha,0.227468,11895146,NCI
9,1,MYC,hgnc:7553,"MYC proto-oncogene, bHLH transcription factor",0.165726,12005453,NCI
10,2,G6PD,hgnc:4057,glucose-6-phosphate dehydrogenase,0.522038,None,PharmGKB

### Parsing ClinVar

For ClinVar, the columns of interest are the UID, the gene, the protein change if any, the type of variant, molecular consequence, classification and the trait. It is critical to know if the variant is pathogenic, drug related or of unknown sigifnicance. This allows for researchers to filter clincially actionable variants.

In [57]:
with open('C:/Users/ian/downloads/clinvar.json', 'r') as file: #opening DGIdbdata file
    data = json.load(file) #loading the file data into a dict
keys = data.keys() #getting the dict keys
print(keys)

dict_keys(['header', 'result'])

In [58]:
data['result']

{'uids': ['3896676',
  '3896669',
  '3896590',
  '3896559',
  '3896552',
  '3896507',
  '3896480',
  '3896467',
  '3896465',
  '3896393'],
 '3896676': {'uid': '3896676',
  'obj_type': 'single nucleotide variant',
  'accession': 'VCV003896676',
  'accession_version': 'VCV003896676.1',
  'title': 'NM_006070.6(TFG):c.723T>C (p.Gly241=)',
  'variation_set': [{'measure_id': '4012544',
    'variation_xrefs': [],
    'variation_name': 'NM_006070.6(TFG):c.723T>C (p.Gly241=)',
    'cdna_change': 'c.723T>C',
    'aliases': [],
    'variation_loc': [{'status': 'current',
      'assembly_name': 'GRCh38',
      'chr': '3',
      'band': '',
      'start': '100744834',
      'stop': '100744834',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '100744834',
      'display_stop': '100744834',
      'assembly_acc_ver': 'GCF_000001405.38',
      'annotation_release': '',
      'alt': '',
      'ref': ''},
     {'status': 'previous',
      'assembly_name': 'GRCh37',
      'chr': '3',
      'band': '',
      'start': '100463678',
      'stop': '100463678',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '100463678',
      'display_stop': '100463678',
      'assembly_acc_ver': 'GCF_000001405.25',
      'annotation_release': '',
      'alt': '',
      'ref': ''}],
    'allele_freq_set': [],
    'variant_type': 'single nucleotide variant',
    'canonical_spdi': 'NC_000003.12:100744833:T:C',
    'common_name': ''}],
  'supporting_submissions': {'scv': ['SCV006074465'], 'rcv': ['RCV005409581']},
  'germline_classification': {'description': 'Uncertain significance',
   'last_evaluated': '2025/04/23 00:00',
   'review_status': 'criteria provided, single submitter',
   'fda_recognized_database': '',
   'trait_set': [{'trait_xrefs': [{'db_source': 'MedGen',
       'db_id': 'CN169374'}],
     'trait_name': 'not specified'}]},
  'clinical_impact_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'oncogenicity_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'record_status': '',
  'gene_sort': 'TFG',
  'chr_sort': '03',
  'location_sort': '00000000000100744834',
  'variation_set_name': '',
  'variation_set_id': '',
  'genes': [{'symbol': 'TFG',
    'geneid': '10342',
    'strand': '+',
    'source': 'submitted'}],
  'molecular_consequence_list': ['synonymous variant'],
  'protein_change': '',
  'fda_recognized_database': ''},
 '3896669': {'uid': '3896669',
  'obj_type': 'single nucleotide variant',
  'accession': 'VCV003896669',
  'accession_version': 'VCV003896669.1',
  'title': 'NM_005816.5(CD96):c.117T>C (p.Ser39=)',
  'variation_set': [{'measure_id': '4012537',
    'variation_xrefs': [],
    'variation_name': 'NM_005816.5(CD96):c.117T>C (p.Ser39=)',
    'cdna_change': 'c.117T>C',
    'aliases': [],
    'variation_loc': [{'status': 'current',
      'assembly_name': 'GRCh38',
      'chr': '3',
      'band': '',
      'start': '111545101',
      'stop': '111545101',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '111545101',
      'display_stop': '111545101',
      'assembly_acc_ver': 'GCF_000001405.38',
      'annotation_release': '',
      'alt': '',
      'ref': ''},
     {'status': 'previous',
      'assembly_name': 'GRCh37',
      'chr': '3',
      'band': '',
      'start': '111263948',
      'stop': '111263948',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '111263948',
      'display_stop': '111263948',
      'assembly_acc_ver': 'GCF_000001405.25',
      'annotation_release': '',
      'alt': '',
      'ref': ''}],
    'allele_freq_set': [],
    'variant_type': 'single nucleotide variant',
    'canonical_spdi': 'NC_000003.12:111545100:T:C',
    'common_name': ''}],
  'supporting_submissions': {'scv': ['SCV006074439'], 'rcv': ['RCV005409574']},
  'germline_classification': {'description': 'Likely benign',
   'last_evaluated': '2025/04/23 00:00',
   'review_status': 'criteria provided, single submitter',
   'fda_recognized_database': '',
   'trait_set': [{'trait_xrefs': [{'db_source': 'MedGen',
       'db_id': 'CN169374'}],
     'trait_name': 'not specified'}]},
  'clinical_impact_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'oncogenicity_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'record_status': '',
  'gene_sort': 'CD96',
  'chr_sort': '03',
  'location_sort': '00000000000111545101',
  'variation_set_name': '',
  'variation_set_id': '',
  'genes': [{'symbol': 'CD96',
    'geneid': '10225',
    'strand': '+',
    'source': 'submitted'}],
  'molecular_consequence_list': ['synonymous variant',
   'non-coding transcript variant'],
  'protein_change': '',
  'fda_recognized_database': ''},
 '3896590': {'uid': '3896590',
  'obj_type': 'single nucleotide variant',
  'accession': 'VCV003896590',
  'accession_version': 'VCV003896590.1',
  'title': 'NM_017563.5(IL17RD):c.1407C>T (p.Ser469=)',
  'variation_set': [{'measure_id': '4012458',
    'variation_xrefs': [],
    'variation_name': 'NM_017563.5(IL17RD):c.1407C>T (p.Ser469=)',
    'cdna_change': 'c.1407C>T',
    'aliases': [],
    'variation_loc': [{'status': 'current',
      'assembly_name': 'GRCh38',
      'chr': '3',
      'band': '',
      'start': '57098296',
      'stop': '57098296',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '57098296',
      'display_stop': '57098296',
      'assembly_acc_ver': 'GCF_000001405.38',
      'annotation_release': '',
      'alt': '',
      'ref': ''},
     {'status': 'previous',
      'assembly_name': 'GRCh37',
      'chr': '3',
      'band': '',
      'start': '57132324',
      'stop': '57132324',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '57132324',
      'display_stop': '57132324',
      'assembly_acc_ver': 'GCF_000001405.25',
      'annotation_release': '',
      'alt': '',
      'ref': ''}],
    'allele_freq_set': [],
    'variant_type': 'single nucleotide variant',
    'canonical_spdi': 'NC_000003.12:57098295:G:A',
    'common_name': ''}],
  'supporting_submissions': {'scv': ['SCV006073794'], 'rcv': ['RCV005409495']},
  'germline_classification': {'description': 'Likely benign',
   'last_evaluated': '2025/04/28 00:00',
   'review_status': 'criteria provided, single submitter',
   'fda_recognized_database': '',
   'trait_set': [{'trait_xrefs': [{'db_source': 'MedGen',
       'db_id': 'CN169374'}],
     'trait_name': 'not specified'}]},
  'clinical_impact_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'oncogenicity_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'record_status': '',
  'gene_sort': 'IL17RD',
  'chr_sort': '03',
  'location_sort': '00000000000057098296',
  'variation_set_name': '',
  'variation_set_id': '',
  'genes': [{'symbol': 'IL17RD',
    'geneid': '54756',
    'strand': '-',
    'source': 'submitted'},
   {'symbol': 'LOC126806689',
    'geneid': '126806689',
    'strand': '+',
    'source': 'submitted'}],
  'molecular_consequence_list': ['synonymous variant'],
  'protein_change': '',
  'fda_recognized_database': ''},
 '3896559': {'uid': '3896559',
  'obj_type': 'single nucleotide variant',
  'accession': 'VCV003896559',
  'accession_version': 'VCV003896559.1',
  'title': 'NM_032383.5(HPS3):c.547A>G (p.Ile183Val)',
  'variation_set': [{'measure_id': '4012427',
    'variation_xrefs': [],
    'variation_name': 'NM_032383.5(HPS3):c.547A>G (p.Ile183Val)',
    'cdna_change': 'c.547A>G',
    'aliases': [],
    'variation_loc': [{'status': 'current',
      'assembly_name': 'GRCh38',
      'chr': '3',
      'band': '',
      'start': '149140333',
      'stop': '149140333',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '149140333',
      'display_stop': '149140333',
      'assembly_acc_ver': 'GCF_000001405.38',
      'annotation_release': '',
      'alt': '',
      'ref': ''},
     {'status': 'previous',
      'assembly_name': 'GRCh37',
      'chr': '3',
      'band': '',
      'start': '148858120',
      'stop': '148858120',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '148858120',
      'display_stop': '148858120',
      'assembly_acc_ver': 'GCF_000001405.25',
      'annotation_release': '',
      'alt': '',
      'ref': ''}],
    'allele_freq_set': [],
    'variant_type': 'single nucleotide variant',
    'canonical_spdi': 'NC_000003.12:149140332:A:G',
    'common_name': ''}],
  'supporting_submissions': {'scv': ['SCV006073364'], 'rcv': ['RCV005409464']},
  'germline_classification': {'description': 'Uncertain significance',
   'last_evaluated': '2025/04/02 00:00',
   'review_status': 'criteria provided, single submitter',
   'fda_recognized_database': '',
   'trait_set': [{'trait_xrefs': [{'db_source': 'MedGen',
       'db_id': 'CN169374'}],
     'trait_name': 'not specified'}]},
  'clinical_impact_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'oncogenicity_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'record_status': '',
  'gene_sort': 'HPS3',
  'chr_sort': '03',
  'location_sort': '00000000000149140333',
  'variation_set_name': '',
  'variation_set_id': '',
  'genes': [{'symbol': 'HPS3',
    'geneid': '84343',
    'strand': '+',
    'source': 'submitted'}],
  'molecular_consequence_list': ['missense variant', 'intron variant'],
  'protein_change': 'I183V',
  'fda_recognized_database': ''},
 '3896552': {'uid': '3896552',
  'obj_type': 'single nucleotide variant',
  'accession': 'VCV003896552',
  'accession_version': 'VCV003896552.1',
  'title': 'NM_000094.4(COL7A1):c.3985G>C (p.Gly1329Arg)',
  'variation_set': [{'measure_id': '4012421',
    'variation_xrefs': [],
    'variation_name': 'NM_000094.4(COL7A1):c.3985G>C (p.Gly1329Arg)',
    'cdna_change': 'c.3985G>C',
    'aliases': [],
    'variation_loc': [{'status': 'previous',
      'assembly_name': 'GRCh37',
      'chr': '3',
      'band': '',
      'start': '48622369',
      'stop': '48622369',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '48622369',
      'display_stop': '48622369',
      'assembly_acc_ver': 'GCF_000001405.25',
      'annotation_release': '',
      'alt': '',
      'ref': ''},
     {'status': 'current',
      'assembly_name': 'GRCh38',
      'chr': '3',
      'band': '',
      'start': '48584936',
      'stop': '48584936',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '48584936',
      'display_stop': '48584936',
      'assembly_acc_ver': 'GCF_000001405.38',
      'annotation_release': '',
      'alt': '',
      'ref': ''}],
    'allele_freq_set': [],
    'variant_type': 'single nucleotide variant',
    'canonical_spdi': 'NC_000003.12:48584935:C:G',
    'common_name': ''}],
  'supporting_submissions': {'scv': ['SCV006073338'], 'rcv': ['RCV005409457']},
  'germline_classification': {'description': 'Uncertain significance',
   'last_evaluated': '2025/04/02 00:00',
   'review_status': 'criteria provided, single submitter',
   'fda_recognized_database': '',
   'trait_set': [{'trait_xrefs': [{'db_source': 'MedGen',
       'db_id': 'CN169374'}],
     'trait_name': 'not specified'}]},
  'clinical_impact_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'oncogenicity_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'record_status': '',
  'gene_sort': 'COL7A1',
  'chr_sort': '03',
  'location_sort': '00000000000048584936',
  'variation_set_name': '',
  'variation_set_id': '',
  'genes': [{'symbol': 'COL7A1',
    'geneid': '1294',
    'strand': '-',
    'source': 'submitted'}],
  'molecular_consequence_list': ['missense variant'],
  'protein_change': 'G1329R',
  'fda_recognized_database': ''},
 '3896507': {'uid': '3896507',
  'obj_type': 'single nucleotide variant',
  'accession': 'VCV003896507',
  'accession_version': 'VCV003896507.1',
  'title': 'NM_001085049.3(MRAS):c.185T>C (p.Ile62Thr)',
  'variation_set': [{'measure_id': '4012376',
    'variation_xrefs': [],
    'variation_name': 'NM_001085049.3(MRAS):c.185T>C (p.Ile62Thr)',
    'cdna_change': 'c.185T>C',
    'aliases': [],
    'variation_loc': [{'status': 'current',
      'assembly_name': 'GRCh38',
      'chr': '3',
      'band': '',
      'start': '138373068',
      'stop': '138373068',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '138373068',
      'display_stop': '138373068',
      'assembly_acc_ver': 'GCF_000001405.38',
      'annotation_release': '',
      'alt': '',
      'ref': ''},
     {'status': 'previous',
      'assembly_name': 'GRCh37',
      'chr': '3',
      'band': '',
      'start': '138091910',
      'stop': '138091910',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '138091910',
      'display_stop': '138091910',
      'assembly_acc_ver': 'GCF_000001405.25',
      'annotation_release': '',
      'alt': '',
      'ref': ''}],
    'allele_freq_set': [],
    'variant_type': 'single nucleotide variant',
    'canonical_spdi': 'NC_000003.12:138373067:T:C',
    'common_name': ''}],
  'supporting_submissions': {'scv': ['SCV006073172'], 'rcv': ['RCV005409412']},
  'germline_classification': {'description': 'Uncertain significance',
   'last_evaluated': '2025/04/03 00:00',
   'review_status': 'criteria provided, single submitter',
   'fda_recognized_database': '',
   'trait_set': [{'trait_xrefs': [{'db_source': 'MedGen',
       'db_id': 'CN169374'}],
     'trait_name': 'not specified'}]},
  'clinical_impact_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'oncogenicity_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'record_status': '',
  'gene_sort': 'MRAS',
  'chr_sort': '03',
  'location_sort': '00000000000138373068',
  'variation_set_name': '',
  'variation_set_id': '',
  'genes': [{'symbol': 'MRAS',
    'geneid': '22808',
    'strand': '+',
    'source': 'submitted'}],
  'molecular_consequence_list': ['missense variant', 'intron variant'],
  'protein_change': 'I62T',
  'fda_recognized_database': ''},
 '3896480': {'uid': '3896480',
  'obj_type': 'single nucleotide variant',
  'accession': 'VCV003896480',
  'accession_version': 'VCV003896480.1',
  'title': 'NM_000404.4(GLB1):c.1010T>A (p.Leu337Gln)',
  'variation_set': [{'measure_id': '4012349',
    'variation_xrefs': [],
    'variation_name': 'NM_000404.4(GLB1):c.1010T>A (p.Leu337Gln)',
    'cdna_change': 'c.1010T>A',
    'aliases': [],
    'variation_loc': [{'status': 'current',
      'assembly_name': 'GRCh38',
      'chr': '3',
      'band': '',
      'start': '33046178',
      'stop': '33046178',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '33046178',
      'display_stop': '33046178',
      'assembly_acc_ver': 'GCF_000001405.38',
      'annotation_release': '',
      'alt': '',
      'ref': ''},
     {'status': 'previous',
      'assembly_name': 'GRCh37',
      'chr': '3',
      'band': '',
      'start': '33087670',
      'stop': '33087670',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '33087670',
      'display_stop': '33087670',
      'assembly_acc_ver': 'GCF_000001405.25',
      'annotation_release': '',
      'alt': '',
      'ref': ''}],
    'allele_freq_set': [],
    'variant_type': 'single nucleotide variant',
    'canonical_spdi': 'NC_000003.12:33046177:A:T',
    'common_name': ''}],
  'supporting_submissions': {'scv': ['SCV006072782'], 'rcv': ['RCV005409385']},
  'germline_classification': {'description': 'Uncertain significance',
   'last_evaluated': '2025/04/04 00:00',
   'review_status': 'criteria provided, single submitter',
   'fda_recognized_database': '',
   'trait_set': [{'trait_xrefs': [{'db_source': 'MedGen',
       'db_id': 'CN169374'}],
     'trait_name': 'not specified'}]},
  'clinical_impact_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'oncogenicity_classification': {'description': '',
   'last_evaluated': '1/01/01 00:00',
   'review_status': '',
   'fda_recognized_database': '',
   'trait_set': []},
  'record_status': '',
  'gene_sort': 'GLB1',
  'chr_sort': '03',
  'location_sort': '00000000000033046178',
  'variation_set_name': '',
  'variation_set_id': '',
  'genes': [{'symbol': 'GLB1',
    'geneid': '2720',
    'strand': '-',
    'source': 'submitted'}],
  'molecular_consequence_list': ['missense variant'],
  'protein_change': 'L206Q, L307Q, L337Q, L385Q',
  'fda_recognized_database': ''},
 '3896467': {'uid': '3896467',
  'obj_type': 'single nucleotide variant',
  'accession': 'VCV003896467',
  'accession_version': 'VCV003896467.1',
  'title': 'NM_183357.3(ADCY5):c.2256+3A>G',
  'variation_set': [{'measure_id': '4012336',
    'variation_xrefs': [],
    'variation_name': 'NM_183357.3(ADCY5):c.2256+3A>G',
    'cdna_change': 'NM_183357.3(ADCY5):c.2256+3A>G',
    'aliases': [],
    'variation_loc': [{'status': 'current',
      'assembly_name': 'GRCh38',
      'chr': '3',
      'band': '',
      'start': '123319671',
      'stop': '123319671',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '123319671',
      'display_stop': '123319671',
      'assembly_acc_ver': 'GCF_000001405.38',
      'annotation_release': '',
      'alt': '',
      'ref': ''},
     {'status': 'previous',
      'assembly_name': 'GRCh37',
      'chr': '3',
      'band': '',
      'start': '123038518',
      'stop': '123038518',
      'inner_start': '',
      'inner_stop': '',
      'outer_start': '',
      'outer_stop': '',
      'display_start': '123038518',
      'display_stop': '123038518',
      'assembly_acc_ver': 'GCF_000001405.25',
      'annotation_release': '',
      'alt': '',
      'ref': ''}],
    'allele_freq_set': [],
    'variant_type': 'single nucleotide variant',
    'canonical_spdi': 'NC_000003.12:123319670:T:C',
    'common_name': ''}],
  'supporting_submissions': {'scv': ['SCV006072759'], 'rcv': ['RCV005409372']},
  'germline_classification': {'description': 'Uncertain significance',
   'last_evaluated': '2025/04/04 00:00',
   'review_status': 'criteria provided, single submitter',
   'fda_recognized_database': '',

In [59]:
#getting the results dictionary
variants = data['result']
uids = variants['uids']

#extracting the relevant data
records = []
for uid in uids:
    v = variants[uid]
    gene_symbol = v['genes'][0]['symbol'] if v.get('genes') else ''
    trait_name = v.get('germline_classification', {}).get('trait_set', [{}])[0].get('trait_name', '')
    
    records.append({
        'uid': uid,
        'accession': v.get('accession'),
        'title': v.get('title'),
        'gene': gene_symbol,
        'protein_change': v.get('protein_change'),
        'variant_type': v.get('obj_type'),
        'molecular_consequence': ', '.join(v.get('molecular_consequence_list', [])),
        'classification': v.get('germline_classification', {}).get('description', ''),
        'trait': trait_name
    })

#converting into a dataframe
df = pd.DataFrame(records)

In [60]:
df #printing the df

,uid,accession,title,gene,protein_change,variant_type,molecular_consequence,classification,trait
0,3896676,VCV003896676,NM_006070.6(TFG):c.723T>C (p.Gly241=),TFG,,single nucleotide variant,synonymous variant,Uncertain significance,not specified
1,3896669,VCV003896669,NM_005816.5(CD96):c.117T>C (p.Ser39=),CD96,,single nucleotide variant,"synonymous variant, non-coding transcript variant",Likely benign,not specified
2,3896590,VCV003896590,NM_017563.5(IL17RD):c.1407C>T (p.Ser469=),IL17RD,,single nucleotide variant,synonymous variant,Likely benign,not specified
3,3896559,VCV003896559,NM_032383.5(HPS3):c.547A>G (p.Ile183Val),HPS3,I183V,single nucleotide variant,"missense variant, intron variant",Uncertain significance,not specified
4,3896552,VCV003896552,NM_000094.4(COL7A1):c.3985G>C (p.Gly1329Arg),COL7A1,G1329R,single nucleotide variant,missense variant,Uncertain significance,not specified
5,3896507,VCV003896507,NM_001085049.3(MRAS):c.185T>C (p.Ile62Thr),MRAS,I62T,single nucleotide variant,"missense variant, intron variant",Uncertain significance,not specified
6,3896480,VCV003896480,NM_000404.4(GLB1):c.1010T>A (p.Leu337Gln),GLB1,"L206Q, L307Q, L337Q, L385Q",single nucleotide variant,missense variant,Uncertain significance,not specified
7,3896467,VCV003896467,NM_183357.3(ADCY5):c.2256+3A>G,ADCY5,,single nucleotide variant,intron variant,Uncertain significance,not specified
8,3896465,VCV003896465,NM_000387.6(SLC25A20):c.463T>C (p.Cys155Arg),SLC25A20,C155R,single nucleotide variant,missense variant,Uncertain significance,not specified
9,3896393,VCV003896393,NM_005816.5(CD96):c.949C>T (p.Leu317=),CD96,,single nucleotide variant,"synonymous variant, non-coding transcript variant",Likely benign,not specified

##### Creating a function

In [62]:
def extract_clinvar_variants(json_path):
    with open(json_path, 'r') as file:
        data = json.load(file)

    variants = data['result']
    uids = variants['uids']

    records = []
    for uid in uids:
        v = variants[uid]
        gene_symbol = v['genes'][0]['symbol'] if v.get('genes') else ''
        trait_set = v.get('germline_classification', {}).get('trait_set', [])
        trait_name = trait_set[0].get('trait_name', '') if trait_set else ''

        records.append({
            'uid': uid,
            'accession': v.get('accession'),
            'title': v.get('title'),
            'gene': gene_symbol,
            'protein_change': v.get('protein_change'),
            'variant_type': v.get('obj_type'),
            'molecular_consequence': ', '.join(v.get('molecular_consequence_list', [])),
            'classification': v.get('germline_classification', {}).get('description', ''),
            'trait': trait_name
        })

    return pd.DataFrame(records)

In [63]:
extract_clinvar_variants('C:/Users/ian/downloads/clinvar.json') #testing the new ClinVar function

,uid,accession,title,gene,protein_change,variant_type,molecular_consequence,classification,trait
0,3896676,VCV003896676,NM_006070.6(TFG):c.723T>C (p.Gly241=),TFG,,single nucleotide variant,synonymous variant,Uncertain significance,not specified
1,3896669,VCV003896669,NM_005816.5(CD96):c.117T>C (p.Ser39=),CD96,,single nucleotide variant,"synonymous variant, non-coding transcript variant",Likely benign,not specified
2,3896590,VCV003896590,NM_017563.5(IL17RD):c.1407C>T (p.Ser469=),IL17RD,,single nucleotide variant,synonymous variant,Likely benign,not specified
3,3896559,VCV003896559,NM_032383.5(HPS3):c.547A>G (p.Ile183Val),HPS3,I183V,single nucleotide variant,"missense variant, intron variant",Uncertain significance,not specified
4,3896552,VCV003896552,NM_000094.4(COL7A1):c.3985G>C (p.Gly1329Arg),COL7A1,G1329R,single nucleotide variant,missense variant,Uncertain significance,not specified
5,3896507,VCV003896507,NM_001085049.3(MRAS):c.185T>C (p.Ile62Thr),MRAS,I62T,single nucleotide variant,"missense variant, intron variant",Uncertain significance,not specified
6,3896480,VCV003896480,NM_000404.4(GLB1):c.1010T>A (p.Leu337Gln),GLB1,"L206Q, L307Q, L337Q, L385Q",single nucleotide variant,missense variant,Uncertain significance,not specified
7,3896467,VCV003896467,NM_183357.3(ADCY5):c.2256+3A>G,ADCY5,,single nucleotide variant,intron variant,Uncertain significance,not specified
8,3896465,VCV003896465,NM_000387.6(SLC25A20):c.463T>C (p.Cys155Arg),SLC25A20,C155R,single nucleotide variant,missense variant,Uncertain significance,not specified
9,3896393,VCV003896393,NM_005816.5(CD96):c.949C>T (p.Leu317=),CD96,,single nucleotide variant,"synonymous variant, non-coding transcript variant",Likely benign,not specified

# All together now

ClinVar, PharmGKB, and DGIdb serves distinct and complementary purposes in the field of pharmacogenomics and personalized medicine. ClinVar focuses on the clinical significance of genetic variants, PharmGKB curates inforamtion on the reltionship between genetic varaintion and drug responses, and DGIdb provides information on the drug-gene interactions. Integrating data from these resoruces provides a hollistic understanding on how genetic variation influences drug therapy, guiding personalzied treatment startegies to minimize adverse reactions.

ClinVar does not provide direct information on how a genetic variant might affect drug response. PharmGKB focuses on drug responses but does not deeply cover disease pathogenicity of variants. DGIdb does not address variant-specific drug response. In total, a single database has it's strength but will not provide the full picture that can be gathered from combining data. ClinVar can identify whether the variant is medically significant whereas PharmGKB can provide explanations for how the variants can influence drug therapy. DGIdb can then determine where the gene can be pharmacologically targetted. This is a multi-layered approach and allows for researchs and clinicians to prioritize variants by filtering by both clinical significance and drug relevance, help guide therapy by matching patients to an optimal treatment plan based on their genomic profile and also mitigate risk by avoiding prescribing medidcations that could trigger adverse reactions on the patient's variants.